import { signOut } from "next-auth/client";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <main className={styles.container}>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello</div>
      <button className="bg-red-500 p-3" onClick={() => signOut()}>
        Sign Out
      </button>
    </main>
  );
}
