import axios from "axios";
import { set } from "mongoose";
import { getSession } from "next-auth/client";
import Head from "next/head";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import Nav from "../src/components/Nav";
import TodoInput from "../src/components/TodoInput";
import TodoItem from "../src/components/TodoItem";

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchTodo = async () => {
      try {
        setLoading(true);
        const res = await axios.get("api/todo");
        console.log(res);
        setTodos(res.data);
        d;
        setLoading(false);
      } catch (e) {
        toast.error(err.response.data.msg);
      }
    };
    fetchTodo();
  }, []);
  return (
    <main>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <TodoInput />
      {todos.map((todo) => (
        <TodoItem key={todo.Id} todo={todo} />
      ))}

      {loading && <h2>Loading...</h2>}
    </main>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
}
